spring.application.name=smart-campus-request-router
# Configuración de RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
# Mantener la aplicación Camel ejecutándose
camel.springboot.main-run-controller=true
# Logs
logging.level.org.apache.camel=INFO
logging.level.ec.udla.integracion.campus=INFO